---
title: "Analysis"
date: "4/7/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(zoo)
library(stargazer)
library(sandwich)
library(lmtest)
library(plm)
library(raster)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(maps)
library(mapproj)
```

```{r, results = F, message = F, warning = F}
setwd('C:/Users/lejac/OneDrive/Documents/Policy-Stats-Team/20_intermediate_data')
final<-read.csv("final_dataset_clean.csv")
```

```{r}
Rang1 <- seq(2001, 2019, 1)
final <- final %>% filter(year %in% Rang1)
final$Date <- as.Date(final$datetime, "%Y-%m-%d")
head(final)
```

```{r}
dim(final)
```
```{r}
final$scale_tanf_fams <- final$percap_tanf_fams * 100000 # Scale the per capita tanf rate to 100,000 inhabitants
final$scale_num_below_fpl <- final$percap_num_below_fpl * 100000 # Scale the per capita number below the federal poverty to 100,000 inhabitants
```

# Exploratory Data Analysis. 

### Missing Data. 

```{r, warning = F, message = F, echo = F}
#Missing variables.
#Code is taken from https://jenslaufer.com/data/analysis/visualize_missing_values_with_ggplot.html (for the subsequent three visualizations).  
MISSINGVALS <- final %>%
    gather(key = "key", value = "val") %>%
    mutate(is.missing = is.na(val)) %>%
    group_by(key, is.missing) %>%
    summarise(num.missing = n()) %>%
    filter(is.missing == T) %>%
    dplyr::select(-is.missing) %>%
    arrange(desc(num.missing))
```

```{r}
MISSINGVALS
```

```{r, warning = F, message = F, fig.height = 3, fig.width = 12}
#Generate a data frame of the percentage of missing values by variable. 
missing.values <- final %>%
  gather(key = "key", value = "val") %>%
  mutate(isna = is.na(val)) %>%
  group_by(key) %>%
  mutate(total = n()) %>%
  group_by(key, total, isna) %>%
  summarise(num.isna = n()) %>%
  mutate(pct = num.isna / total * 100)

levels <- (missing.values  %>% filter(isna == T) %>% arrange(desc(pct)))$key

#Visualize! 
percent_missing <- missing.values %>%
      ggplot() +
  geom_bar(aes(x = reorder(key, desc(pct)), 
                     y = pct, fill=isna), 
                 stat = 'identity', alpha=0.8) +
      scale_x_discrete(limits = levels) +
      scale_fill_manual(name = "", 
                        values = c('steelblue', 'navy'), labels = c("Recorded", "Missing")) +
      coord_flip() +
      labs(title = "Missing Values: Percentage of Variable", x =
             'Variable', y = "Percentage of Missing Values") + 
  theme(plot.title = element_text(hjust = 0.5))

#Identify and visualize missing data by row. 
missingbyrow <- final %>%
  mutate(id = row_number()) %>%
  gather(-id, key = "key", value = "val") %>%
  mutate(isna = is.na(val)) %>%
  ggplot(aes(key, id, fill = isna)) +
    geom_raster(alpha=0.8) +
    scale_fill_manual(name = "",
        values = c('dodgerblue', 'gold'),
        labels = c("Recorded", "Missing")) +
    scale_x_discrete(limits = levels) +
    labs(x = "Variable",
           y = "Row Number", title = "Missing Values by Row") +
    coord_flip() + theme(plot.title = element_text(hjust = 0.5))

#Plot. 
grid.arrange(percent_missing, missingbyrow, ncol = 2, nrow = 1)
```

```{r, warning = F, message = F}
Plot1 <- ggplot(data = final, mapping = aes(x = year, y = num_below_fpl, color = state)) + geom_point() + geom_line() + theme(legend.position = "none") + labs(x = 'Year', y = "Number Below Federal Poverty Line", title = 'Number Below Federal Poverty Line by State') + theme(plot.title = element_text(hjust = 0.5))
Plot1
```

```{r, warning = F, message = F}
Plot2 <- ggplot(data = final, mapping = aes(x = year, y = unemp_rate, color = state)) + geom_point() + theme(legend.position = "none") + labs(x = 'Year', y = "Number Below Federal Poverty Line", title = 'Number Below Federal Poverty Line by State') + theme(plot.title = element_text(hjust = 0.5))
Plot2
```

```{r}
final <- final %>% drop_na()
max(final$scale_tanf_fams)
```

```{r, warning = F, message = F, fig.height = 3, fig.width = 10}
xfit <- seq(-10, max(final$scale_tanf_fams), length = 100) 
yfit <- dnorm(xfit, mean = mean(final$scale_tanf_fams), sd = sd(final$scale_tanf_fams)) 

CountPlot <- ggplot() + geom_histogram(aes(x = final$scale_tanf_fams), fill = "slategray3") + geom_line(aes(x = xfit, y = yfit*2000*900), col = "darkblue", size = 1) + labs(x = 'TANF Familes Per Capita Scaled to 100,000', y = 'Frequency', title = 'Histogram of TANF Families Per Capita \n Scaled to 100,000') + theme(plot.title = element_text(hjust = 0.5))

#Generate a normal probability plot. 
QPlot <- ggplot() +
  geom_qq(aes(sample = final$scale_tanf_fams), col = "darkblue") +
  geom_qq_line(aes(sample = final$scale_tanf_fams), col = 'darkred') + labs(x = 'Theoretical', y = 'Sample', title = 'Q-Q Normality Plot') + theme(plot.title = element_text(hjust = 0.5))

grid.arrange(CountPlot, QPlot, ncol = 2, nrow = 1)
```

```{r}
#There are some values that are equal to 0; check that these are missing 
#within the raw data and omit (major outliers). 
Test <- final %>% filter(tanf_fams == 0)

final <- final %>% filter(tanf_fams != 0)
```


```{r}
#Log-transform: 
final$Scaled_LogFam <- log(final$scale_tanf_fams)
```

```{r}
min(final$Scaled_LogFam)
```
```{r, warning = F, message = F, fig.height = 3, fig.width = 10}
xfit <- seq(min(final$Scaled_LogFam), max(final$Scaled_LogFam), length = 100) 
yfit <- dnorm(xfit, mean = mean(final$Scaled_LogFam), sd = sd(final$Scaled_LogFam)) 

CountPlot <- ggplot() + geom_histogram(aes(x = final$Scaled_LogFam), fill = "slategray3") + geom_line(aes(x = xfit, y = yfit*2000), col = "darkblue", size = 1) + labs(x = 'TANF Familes Per Capita Scaled to 100,000', y = 'Frequency', title = 'Histogram of TANF Families Per Capita \n Scaled to 100,000') + theme(plot.title = element_text(hjust = 0.5))

#Generate a normal probability plot. 
QPlot <- ggplot() +
  geom_qq(aes(sample = final$Scaled_LogFam), col = "darkblue") +
  geom_qq_line(aes(sample = final$Scaled_LogFam), col = 'darkred') + labs(x = 'Theoretical', y = 'Sample', title = 'Q-Q Normality Plot') + theme(plot.title = element_text(hjust = 0.5))

grid.arrange(CountPlot, QPlot, ncol = 2, nrow = 1)
```

```{r}
Policy <- final %>% filter(drug_law == 1)
Policy_States <- unique(Policy$state)

NoPol <- final %>% filter(drug_law == 0)
NoPolicy_States <- unique(NoPol$state)
```

```{r}
CapStr <- function(y) {
  c <- strsplit(y, " ")[[1]]
  paste(toupper(substring(c, 1,1)), substring(c, 2),
      sep="", collapse=" ")
}

us_states <- map_data("state")
us_states$region <- sapply(us_states$region, CapStr)

IndList <- c()
for (i in us_states$region) {
  if (i %in% Policy_States){
    IndList <- c(IndList, 1)
  }
  else {
    IndList <- c(IndList, 0)
  }
}

us_states$drug_law <- as.factor(IndList)
head(us_states)
```

```{r}
#BCD2CB (blueish) and #364C54 (dark muted green/blue) and #D7E8C4 (green) and dark grey
Sam_Cols <- c("Blueish" = '#BCD2CB', 'DarkGreen' = '#364C54', 'Green' = '#D7E8C4')

p <- ggplot(data = us_states,
            aes(x = long, y = lat,
                group = group, fill = drug_law)) + geom_polygon(color = "white", size = 0.20, alpha = 0.75) + coord_map() + labs(x = '', y = '', title = 'State Drug Law Enaction') + theme_classic() + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_manual(name = 'Policy Status', labels = c('No', 'Yes'), values = c('#D7E8C4', '#364C54'))
p
```

## Case: Tennessee. 

Control Region: 

```{r}
Region1Overall <- c('Kentucky', 'Virginia', 'South Carolina', 'Louisiana')

InterList <- c()
for (i in us_states$region) {
  if (i == 'Tennessee') {
    InterList <- c(InterList, 1)
  }
  else if (i %in% Region1Overall) {
    InterList <- c(InterList, 2)
  }
  else {
    InterList <- c(InterList, 3)
  }
}

us_states$TNRegion <- as.factor(InterList) 
```

```{r}
pTN <- ggplot(data = us_states,
            aes(x = long, y = lat,
                group = group, fill = TNRegion)) + geom_polygon(color = "white", size = 0.20, alpha = 0.75) + coord_map() + labs(x = '', y = '', title = 'Tennessee and Control States') + theme_classic() + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_manual(name = 'State Group', labels = c('Tennessee', 'Control States', 'Non-Control States'), values = c('#364C54', '#BCD2CB', 'darkgray'))
```

```{r}
R1 <- final %>% filter(state %in% Region1Overall) 

TN <- final %>% filter(state == 'Tennessee') 

TNPre <- TN %>% filter(Date <= '2014-07-01')
ControlPre <- R1 %>% filter(Date <= '2014-07-01')

#Define breakpoint. 

TNPost <- TN %>% filter(Date >= '2015-01-01')
ControlPost <- R1 %>% filter(Date >= '2015-01-01')
```

```{r, warning = F, message = F}
cols <- c("Tennessee" = '#364C54', "Control Region" = "#BCD2CB")
RegInit <- ggplot() + stat_smooth(TNPre, mapping = aes(x = Date, y = Scaled_LogFam, fill = 'Tennessee', group = 1),
  color = "darkgray", size = 0.20, alpha = 0.75, 
  method = "loess") + stat_smooth(TNPost, mapping = aes(x = Date, y = Scaled_LogFam, fill = 'Tennessee', group = 1),
  color = "darkgray", size = 0.20, alpha = 0.75,   
  method = "loess"
  ) + stat_smooth(ControlPre, mapping = aes(x = Date, y = Scaled_LogFam, fill = 'Control Region', group = 1),
  color = "darkgray", size = 0.20,
  method = "loess"
  ) + geom_vline(xintercept = as.Date('2014-07-01'), linetype="dashed", 
                color = "black", size=0.50) + geom_vline(xintercept = as.Date('2015-01-01'), linetype="dashed", 
                color = "black", size=0.50) + stat_smooth(ControlPost, mapping = aes(x = Date, y = Scaled_LogFam, fill = 'Control Region', group = 1),
  color = "darkgray", size = 0.20, 
  method = "loess"
  ) + labs(x = 'Date', y = 'Percent of Families on TANF', title = 'Linear Time Trends for Percent of Families on TANF: \n Tennessee and Control Region') + theme_classic() + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_manual(name="State Group",values=cols)
```

```{r, fig.height = 3, fig.width = 12, warning = F, message = F}
grid.arrange(pTN, RegInit, ncol = 2, nrow = 1)
```


## Case: North Carolina. 

Control Region: Kentucky, South Carolina, Indiana. 

```{r}
Region1Overall <- c('Kentucky', 'South Carolina', 'Indiana')

InterList <- c()
for (i in us_states$region) {
  if (i == 'North Carolina') {
    InterList <- c(InterList, 1)
  }
  else if (i %in% Region1Overall) {
    InterList <- c(InterList, 2)
  }
  else {
    InterList <- c(InterList, 3)
  }
}

us_states$NCRegion <- as.factor(InterList) 
```

```{r}
p <- ggplot(data = us_states,
            aes(x = long, y = lat,
                group = group, fill = NCRegion)) + geom_polygon(color = "white", size = 0.20, alpha = 0.75) + coord_map() + labs(x = '', y = '', title = 'North Carolina and Control States') + theme_classic() + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_manual(name = 'State Group', labels = c('North Carolina', 'Control States', 'Non-Control States'), values = c('#364C54', '#BCD2CB', 'darkgray'))
```


```{r}
Region1 <- c('Kentucky', 'South Carolina', 'Indiana')

R1 <- final %>% filter(state %in% Region1) 

WV <- final %>% filter(state == 'North Carolina') 

WVPre <- WV %>% filter(Date <= '2013-07-01')
ControlPre <- R1 %>% filter(Date <= '2013-07-01')

#Define breakpoint. 

WVPost <- WV %>% filter(Date >= '2014-01-01')
ControlPost <- R1 %>% filter(Date >= '2014-01-01')
```

```{r, message = F, warning = F}
cols <- c("North Carolina" = '#364C54', "Control Region" = "#BCD2CB")
RegInit <- ggplot() + stat_smooth(WVPre, mapping = aes(x = Date, y = Scaled_LogFam, fill = 'North Carolina', group = 1),
  color = "darkgray", size = 0.20,
  method = "loess") + stat_smooth(WVPost, mapping = aes(x = Date, y = Scaled_LogFam, fill = 'North Carolina', group = 1),
  color = "darkgray", size = 0.20, 
  method = "loess"
  ) + stat_smooth(ControlPre, mapping = aes(x = Date, y = Scaled_LogFam, fill = 'Control Region', group = 1),
  color = "darkgray", size = 0.20,
  method = "loess"
  ) + geom_vline(xintercept = as.Date('2013-07-01'), linetype="dashed", 
                color = "black", size=0.50) + geom_vline(xintercept = as.Date('2014-01-01'), linetype="dashed", 
                color = "black", size=0.50) + stat_smooth(ControlPost, mapping = aes(x = Date, y = Scaled_LogFam, fill = 'Control Region', group = 1),
  color = "darkgray", size = 0.20, 
  method = "loess"
  ) + labs(x = 'Date', y = 'Percent of Families on TANF', title = 'Linear Time Trends for Percent of Families on TANF: \n North Carolina and Control Region') + theme_classic() + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_manual(name="State Group",values=cols)
```

```{r, fig.height = 3, fig.width = 12, warning = F, message = F}
grid.arrange(p, RegInit, ncol = 2, nrow = 1)
```

```{r}
StatesList <- c('North Carolina', 'Kentucky', 'South Carolina', 'Indiana')
TC <- final %>% filter(state %in% StatesList)
```

```{r}
PList <- c()
Enact_Date <- '2013-07-01'
for (i in TC$Date){
  if (i > Enact_Date){
    PList <- c(PList, 1)
  }
  else {
    PList <- c(PList, 0)
  }
}

TC$Post_Ind <- as.factor(PList)
```

```{r}
#TBD. 
```










# Save

```{r}
print("done")
```

